name: Doxygen completeness

on: [push, pull_request]

jobs:
  doxygen:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build doxygen HTML
      run: |
        cd docs
        doxygen

    - name: Report doxygen errors
      run: |
        cat docs/doxygen.log
        test ! -s docs/doxygen.log
